"""add recurring income rules

Revision ID: 1abac0ac574c
Revises: c41a1f1187e7
Create Date: 2026-08-19 18:29:16.277826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1abac0ac574c'
down_revision: Union[str, Sequence[str], None] = 'c41a1f1187e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_income_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_day', sa.Integer(), nullable=False),
    sa.Column('transaction_keyword', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expected_amount > 0', name='check_recurring_income_expected_amount_positive'),
    sa.CheckConstraint('expected_day >= 1 AND expected_day <= 31', name='check_recurring_income_expected_day'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_income_rules_id'), 'recurring_income_rules', ['id'], unique=False)
    op.add_column('incomes', sa.Column('recurring_income_rule_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incomes', 'recurring_income_rules', ['recurring_income_rule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.drop_column('incomes', 'recurring_income_rule_id')
    op.drop_index(op.f('ix_recurring_income_rules_id'), table_name='recurring_income_rules')
    op.drop_table('recurring_income_rules')
    # ### end Alembic commands ###
