"""link expenses to bank transactions

Revision ID: 477a89a6793b
Revises: 5cd61f91a8e0
Create Date: 2026-08-19 13:50:27.041067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477a89a6793b'
down_revision: Union[str, Sequence[str], None] = '5cd61f91a8e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('bank_transaction_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'expenses', ['bank_transaction_id'])
    op.create_foreign_key(None, 'expenses', 'bank_transactions', ['bank_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='unique')
    op.drop_column('expenses', 'bank_transaction_id')
    # ### end Alembic commands ###
