"""allow income expected date to be null

Revision ID: 574c670c601e
Revises: ff7e8fa0f358
Create Date: 2026-08-20 12:16:37.785354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574c670c601e'
down_revision: Union[str, Sequence[str], None] = 'ff7e8fa0f358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incomes', 'expected_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incomes', 'expected_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
