"""add system flag to categories

Revision ID: 5cd61f91a8e0
Revises: f6f4ccad7c4f
Create Date: 2026-08-18 23:37:02.361530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd61f91a8e0'
down_revision: Union[str, Sequence[str], None] = 'f6f4ccad7c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "categories",
        sa.Column(
            "is_system",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )

    op.alter_column(
        "categories",
        "is_system",
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_system')
    # ### end Alembic commands ###
