"""create bank transactions table

Revision ID: acf5a8dd3c00
Revises: 7ff338af1411
Create Date: 2026-08-18 18:54:29.295023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf5a8dd3c00'
down_revision: Union[str, Sequence[str], None] = '7ff338af1411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('direction', sa.Enum('INCOMING', 'OUTGOING', name='banktransactiondirection'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_bank_transaction_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'external_transaction_id', name='uq_bank_transaction_user_provider_external_id')
    )
    op.create_index(op.f('ix_bank_transactions_id'), 'bank_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transactions_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    # ### end Alembic commands ###
