"""add value date to bank transactions

Revision ID: c41a1f1187e7
Revises: 477a89a6793b
Create Date: 2026-08-19 14:45:29.428036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41a1f1187e7'
down_revision: Union[str, Sequence[str], None] = '477a89a6793b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('value_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_transactions', 'value_date')
    # ### end Alembic commands ###
