"""prevent duplicate recurring incomes

Revision ID: e162d57fd5d1
Revises: 1abac0ac574c
Create Date: 2026-08-19 19:13:41.392869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e162d57fd5d1'
down_revision: Union[str, Sequence[str], None] = '1abac0ac574c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_income_recurring_rule_expected_date', 'incomes', ['recurring_income_rule_id', 'expected_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_income_recurring_rule_expected_date', 'incomes', type_='unique')
    # ### end Alembic commands ###
