"""create categorization rules table

Revision ID: f6f4ccad7c4f
Revises: acf5a8dd3c00
Create Date: 2026-08-18 23:15:15.062349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f4ccad7c4f'
down_revision: Union[str, Sequence[str], None] = 'acf5a8dd3c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
