"""link incomes to bank transactions

Revision ID: ff7e8fa0f358
Revises: e162d57fd5d1
Create Date: 2026-08-20 11:22:43.834656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7e8fa0f358'
down_revision: Union[str, Sequence[str], None] = 'e162d57fd5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('bank_transaction_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'incomes', ['bank_transaction_id'])
    op.create_foreign_key(None, 'incomes', 'bank_transactions', ['bank_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.drop_constraint(None, 'incomes', type_='unique')
    op.drop_column('incomes', 'bank_transaction_id')
    # ### end Alembic commands ###
